---
# Variables for the routers mpls-cloud and inet-cloud.
# These routers are used to mock Service Providers in the example.
spine:
  defaults:
    platform: vEOS-lab
    loopback_ipv4_pool: 172.31.255.0/24
  nodes:
    - name: mpls-cloud
      id: 22
      bgp_as: 65042
      mgmt_ip: 192.168.17.30/24
      l3_interfaces:
        - name: Ethernet1
          description: pf1-Ethernet1
          ip_address: 172.18.100.1/24
        - name: Ethernet2
          description: pf2-Ethernet1
          ip_address: 172.18.200.1/24
        - name: Ethernet5
          description: site1-wan1-Ethernet3
          ip_address: 172.18.10.1/24
        - name: Ethernet6
          description: site1-wan2-Ethernet3
          ip_address: 172.18.11.1/24
        - name: Ethernet7
          description: site2-wan1-Ethernet3
          ip_address: 172.18.20.1/24
        - name: Ethernet8
          description: site4-wan1-Ethernet3
          ip_address: 172.18.40.1/24
    - name: inet-cloud
      id: 23
      bgp_as: 65666
      mgmt_ip: 192.168.17.31/24
      l3_interfaces:
        - name: Ethernet1
          description: pf1-Ethernet2
          ip_address: 100.64.100.1/24
        - name: Ethernet2
          description: pf2-Ethernet2
          ip_address: 100.64.200.1/24
        - name: Ethernet5
          description: site1-wan1-Ethernet4
          ip_address: 100.64.10.1/24
          structured_config:
            dhcp_server_ipv4: true
        - name: Ethernet6
          description: site1-wan2-Ethernet4
          ip_address: 100.64.11.1/24
          structured_config:
            dhcp_server_ipv4: true
        - name: Ethernet7
          description: site2-wan2-Ethernet4
          ip_address: 100.64.21.1/24
        - name: Ethernet10
          description: site4-wan1-Ethernet4
          ip_address: 100.64.40.1/24
      l3_port_channels:
        - name: Port-Channel8
          mode: active
          description: site3-wan1-Port-Channel4
          member_interfaces:
            - name: Ethernet8
            - name: Ethernet9
          ip_address: 100.64.30.1/24
          structured_config:
            dhcp_server_ipv4: true
      structured_config:
        router_bgp:
          # Neighbor definition for site2-wan2
          neighbors:
            - ip_address: 100.64.21.2
              remote_as: 65000
              peer_group: IPv4-UNDERLAY-PEERS
              default_originate:
                enabled: true
                always: true
        dhcp_servers:
          - disabled: false
            vrf: default
            lease_time_ipv4:
              days: 6
              hours: 23
              minutes: 59
            subnets:
              - subnet: 100.64.10.0/24
                name: 10 NET
                default_gateway: 100.64.10.1
                ranges:
                  - start: 100.64.10.2
                    end: 100.64.10.2
              - subnet: 100.64.11.0/24
                name: 11 NET
                default_gateway: 100.64.11.1
                ranges:
                  - start: 100.64.11.2
                    end: 100.64.11.2
              - subnet: 100.64.30.0/24
                name: 30 NET
                default_gateway: 100.64.30.1
                ranges:
                  - start: 100.64.30.2
                    end: 100.64.30.2
